[package]
name = "gpukit_derive"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.74" }
proc-macro2 = "1.0.28"
quote = "1.0.9"
